export interface Property {
  id: number;
  title: string;
  price: string;
  location: string;
  type: 'Rumah' | 'Apartemen' | 'Villa';
  beds: number;
  baths: number;
  sqft: number;
  image: string;
  isFeatured?: boolean;
  description: string;
}

export const properties: Property[] = [
  // ... (1-24 data sebelumnya tetap ada, saya tambahkan mulai dari 25)
  {
    id: 1,
    title: "Modern Minimalist Villa",
    price: "Rp 12.500.000.000",
    location: "Canggu, Bali",
    type: "Villa",
    beds: 4,
    baths: 5,
    sqft: 450,
    image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/596232996.jpg?k=dd9136e37ce13540e66031ecc87635be4daa6cdaadbe237a9ccf0201e03a771f&o=",
    isFeatured: false,
    description: "Villa modern dengan kolam renang infinity menghadap sawah, desain open-space yang mewah."
  },
  {
    id: 2,
    title: "Luxury Penthouse SCBD",
    price: "Rp 45.000.000.000",
    location: "Jakarta Selatan",
    type: "Apartemen",
    beds: 3,
    baths: 3,
    sqft: 280,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Penthouse eksklusif di jantung bisnis Jakarta dengan pemandangan kota 360 derajat."
  },
  {
    id: 3,
    title: "Classic European House",
    price: "Rp 8.200.000.000",
    location: "Dago, Bandung",
    type: "Rumah",
    beds: 5,
    baths: 4,
    sqft: 350,
    image: "https://www.houseplans.net/uploads/plans/31614/elevations/87103-768.jpg?v=071524102034",
    isFeatured: false,
    description: "Rumah bergaya kolonial modern dengan udara sejuk dan taman luas di belakang."
  },
  {
    id: 4,
    title: "Industrial Loft Studio",
    price: "Rp 1.800.000.000",
    location: "Tangerang Selatan",
    type: "Apartemen",
    beds: 1,
    baths: 1,
    sqft: 45,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Unit apartemen gaya industrial cocok untuk eksekutif muda atau pasangan baru."
  },
  {
    id: 5,
    title: "Tropical Garden Residence",
    price: "Rp 5.500.000.000",
    location: "Ubud, Bali",
    type: "Rumah",
    beds: 3,
    baths: 3,
    sqft: 200,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Hunian asri menyatu dengan alam, material kayu premium dan batu alam."
  },
  {
    id: 6,
    title: "Smart Home Cluster",
    price: "Rp 3.100.000.000",
    location: "Surabaya Barat",
    type: "Rumah",
    beds: 3,
    baths: 2,
    sqft: 120,
    image: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Rumah pintar dengan teknologi terkini, keamanan 24 jam dan fasilitas clubhouse."
  },
  {
    id: 7,
    title: "Ocean View Mansion",
    price: "Rp 25.000.000.000",
    location: "Uluwatu, Bali",
    type: "Villa",
    beds: 6,
    baths: 7,
    sqft: 800,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Mansion megah dengan pemandangan laut lepas dan akses pribadi ke pantai."
  },
  {
    id: 8,
    title: "Skyscraper Residence",
    price: "Rp 4.200.000.000",
    location: "Medan, Sumatera Utara",
    type: "Apartemen",
    beds: 2,
    baths: 2,
    sqft: 90,
    image: "https://images.skyscrapercenter.com/building/bellagio_ext_full-2_9027.jpg",
    isFeatured: false,
    description: "Hunian vertikal strategis di pusat kota Medan dengan fasilitas lengkap."
  },
  {
    id: 9,
    title: "Pine Forest Cottage",
    price: "Rp 2.500.000.000",
    location: "Lembang, Bandung",
    type: "Rumah",
    beds: 2,
    baths: 1,
    sqft: 150,
    image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/440289070.jpg?k=5bd0efbb165b62c51fbbd4599383c9ae768c845e42365dce6bde0af71094cd53&o=",
    isFeatured: false,
    description: "Cottage kayu yang hangat di tengah hutan pinus Lembang yang asri."
  },
  {
    id: 10,
    title: "Urban Executive Suite",
    price: "Rp 7.800.000.000",
    location: "Menteng, Jakarta Pusat",
    type: "Apartemen",
    beds: 2,
    baths: 2,
    sqft: 110,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Suite mewah di kawasan elit Menteng untuk kenyamanan eksekutif."
  },
  {
    id: 11,
    title: "Green Valley Estate",
    price: "Rp 1.500.000.000",
    location: "Sleman, Yogyakarta",
    type: "Rumah",
    beds: 3,
    baths: 2,
    sqft: 100,
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Hunian nyaman dengan lingkungan hijau dan view gunung Merapi."
  },
  {
    id: 12,
    title: "Modern Zen Villa",
    price: "Rp 9.000.000.000",
    location: "Seminyak, Bali",
    type: "Villa",
    beds: 3,
    baths: 3,
    sqft: 300,
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Villa dengan desain zen yang menenangkan, cocok untuk investasi sewa harian."
  },
  {
    id: 13,
    title: "The Heritage Mansion",
    price: "Rp 32.000.000.000",
    location: "Kemang, Jakarta Selatan",
    type: "Rumah",
    beds: 6,
    baths: 6,
    sqft: 1200,
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Rumah megah dengan arsitektur klasik di lingkungan asri Kemang."
  },
  {
    id: 14,
    title: "Sunset Edge Villa",
    price: "Rp 18.500.000.000",
    location: "Jimbaran, Bali",
    type: "Villa",
    beds: 4,
    baths: 4,
    sqft: 500,
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Nikmati sunset setiap hari dari balkon kamar Anda di Villa tepi tebing ini."
  },
  {
    id: 15,
    title: "Neo City Apartment",
    price: "Rp 2.400.000.000",
    location: "BSD City, Tangerang",
    type: "Apartemen",
    beds: 2,
    baths: 1,
    sqft: 68,
    image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Apartemen modern dengan akses langsung ke mall dan perkantoran."
  },
  {
    id: 16,
    title: "Scandinavian Lake House",
    price: "Rp 6.700.000.000",
    location: "Sentul City, Bogor",
    type: "Rumah",
    beds: 4,
    baths: 3,
    sqft: 280,
    image: "https://st.hzcdn.com/simgs/81d1e5dc0a04cc5b_14-2426/home-design.jpg",
    isFeatured: false,
    description: "Desain Skandinavia yang bersih dengan view danau dan pegunungan."
  },
  {
    id: 17,
    title: "Sky Garden Residence",
    price: "Rp 15.000.000.000",
    location: "Sudirman, Jakarta",
    type: "Apartemen",
    beds: 3,
    baths: 3,
    sqft: 180,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Tinggal di atas awan dengan taman gantung pribadi di setiap unit."
  },
  {
    id: 18,
    title: "Mountain Breeze Villa",
    price: "Rp 4.800.000.000",
    location: "Batu, Malang",
    type: "Villa",
    beds: 3,
    baths: 2,
    sqft: 220,
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Udara pegunungan yang segar dan tenang, cocok untuk peristirahatan keluarga."
  },
  {
    id: 19,
    title: "Modern Coastal Home",
    price: "Rp 11.200.000.000",
    location: "PIK 2, Jakarta Utara",
    type: "Rumah",
    beds: 5,
    baths: 5,
    sqft: 400,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Hunian prestisius di kawasan mandiri terbaru dengan fasilitas pantai pasir putih."
  },
  {
    id: 20,
    title: "The Glass House",
    price: "Rp 7.500.000.000",
    location: "Kuta, Lombok",
    type: "Villa",
    beds: 2,
    baths: 2,
    sqft: 180,
    image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Villa ikonik dengan dinding kaca penuh, menghadap ke teluk Kuta Lombok."
  },
  {
    id: 21,
    title: "Minimalist City Flat",
    price: "Rp 1.200.000.000",
    location: "Thamrin, Jakarta Pusat",
    type: "Apartemen",
    beds: 1,
    baths: 1,
    sqft: 38,
    image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/622191408.jpg?k=42ac8e704d4266c76df3704f270c23e89a8145dfe85fc97acf91aa09dbeea6bf&o=",
    isFeatured: false,
    description: "Efisien dan elegan, pilihan utama bagi profesional yang bekerja di pusat kota."
  },
  {
    id: 22,
    title: "Balikpapan Bay Estate",
    price: "Rp 5.200.000.000",
    location: "Balikpapan, Kalimantan Timur",
    type: "Rumah",
    beds: 4,
    baths: 3,
    sqft: 300,
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Hunian eksklusif dengan view teluk Balikpapan dekat kawasan IKN."
  },
  {
    id: 23,
    title: "Javanese Royal Villa",
    price: "Rp 14.000.000.000",
    location: "Borobudur, Magelang",
    type: "Villa",
    beds: 5,
    baths: 5,
    sqft: 600,
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Arsitektur tradisional Joglo dengan sentuhan modern mewah dekat Candi Borobudur."
  },
  {
    id: 24,
    title: "Grand Riverside Apartment",
    price: "Rp 3.800.000.000",
    location: "Pakuwon, Surabaya",
    type: "Apartemen",
    beds: 2,
    baths: 2,
    sqft: 85,
    image: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Hunian nyaman dengan fasilitas bintang 5 di kawasan superblock Surabaya Timur."
  },
  {
    id: 25,
    title: "Samarinda Hill Residence",
    price: "Rp 2.800.000.000",
    location: "Samarinda, Kalimantan Timur",
    type: "Rumah",
    beds: 3,
    baths: 2,
    sqft: 180,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Rumah modern di atas bukit dengan sirkulasi udara terbaik di Samarinda."
  },
  {
    id: 26,
    title: "Makassar Waterfront Condo",
    price: "Rp 3.500.000.000",
    location: "Pantai Losari, Makassar",
    type: "Apartemen",
    beds: 2,
    baths: 2,
    sqft: 75,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Apartemen eksklusif dengan view langsung ke ikon kota Makassar, Pantai Losari."
  },
  {
    id: 27,
    title: "Manado Bay View Villa",
    price: "Rp 6.200.000.000",
    location: "Manado, Sulawesi Utara",
    type: "Villa",
    beds: 4,
    baths: 3,
    sqft: 320,
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/b0/23/2b/caption.jpg?w=1200&h=-1&s=1",
    isFeatured: false,
    description: "Villa cantik menghadap laut Sulawesi, hanya 15 menit dari pusat kota Manado."
  },
  {
    id: 28,
    title: "Palembang Riverside House",
    price: "Rp 1.900.000.000",
    location: "Palembang, Sumatera Selatan",
    type: "Rumah",
    beds: 3,
    baths: 2,
    sqft: 140,
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Rumah minimalis di kawasan berkembang dekat Jembatan Ampera."
  },
  {
    id: 29,
    title: "Batam Harbour View Condo",
    price: "Rp 2.100.000.000",
    location: "Batam Center, Kepulauan Riau",
    type: "Apartemen",
    beds: 2,
    baths: 1,
    sqft: 60,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Hunian vertikal premium dengan pemandangan kapal feri dan Singapura di kejauhan."
  },
  {
    id: 30,
    title: "Jayapura Peak Mansion",
    price: "Rp 8.500.000.000",
    location: "Jayapura, Papua",
    type: "Rumah",
    beds: 5,
    baths: 4,
    sqft: 400,
    image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    description: "Hunian termewah di Jayapura dengan view Teluk Youtefa yang memukau."
  },
  {
    id: 31,
    title: "Pontianak Riverfront Villa",
    price: "Rp 4.300.000.000",
    location: "Pontianak, Kalimantan Barat",
    type: "Villa",
    beds: 3,
    baths: 3,
    sqft: 250,
    image: "https://images.unsplash.com/photo-1512914890251-2f96a9b0bbe2?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Villa unik di tepi sungai Kapuas, memadukan gaya modern dan kearifan lokal."
  },
  {
    id: 32,
    title: "Ambon Seaside Residence",
    price: "Rp 3.700.000.000",
    location: "Ambon, Maluku",
    type: "Rumah",
    beds: 4,
    baths: 3,
    sqft: 210,
    image: "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Rumah nyaman dengan akses privat ke pantai berpasir putih Ambon."
  },
  {
    id: 33,
    title: "Lampung Hills View",
    price: "Rp 1.600.000.000",
    location: "Bandar Lampung, Lampung",
    type: "Rumah",
    beds: 3,
    baths: 2,
    sqft: 120,
    image: "https://astraotoshop.com/asset/article-aop/wisata-lampung-yang-wajib-dikunjungi_20241017.webp",
    isFeatured: false,
    description: "Cluster eksklusif di perbukitan dengan pemandangan kota dan teluk Lampung."
  },
  {
    id: 34,
    title: "Banjarmasin Water Village",
    price: "Rp 2.900.000.000",
    location: "Banjarmasin, Kalimantan Selatan",
    type: "Villa",
    beds: 3,
    baths: 2,
    sqft: 190,
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Villa bergaya panggung modern di kawasan elit pinggir sungai."
  },
  {
    id: 35,
    title: "Pekanbaru Executive Mansion",
    price: "Rp 5.800.000.000",
    location: "Pekanbaru, Riau",
    type: "Rumah",
    beds: 5,
    baths: 4,
    sqft: 350,
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Rumah dengan halaman sangat luas dan kolam renang pribadi di pusat kota Riau."
  },
  {
    id: 36,
    title: "Mataram Oasis Apartment",
    price: "Rp 1.400.000.000",
    location: "Mataram, Lombok",
    type: "Apartemen",
    beds: 1,
    baths: 1,
    sqft: 45,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Apartemen pertama di Lombok dengan konsep resort hijau di tengah kota."
  },
  {
    id: 37,
    title: "Kupang Ocean Breeze",
    price: "Rp 2.200.000.000",
    location: "Kupang, NTT",
    type: "Rumah",
    beds: 3,
    baths: 2,
    sqft: 160,
    image: "https://images.tokopedia.net/blog-tokopedia-com/uploads/2018/09/wisata-kupang-6-Indonesia-Kaya.jpg",
    isFeatured: false,
    description: "Rumah bergaya minimalis tropis dengan balkon luas menghadap laut Kupang."
  },
  {
    id: 38,
    title: "Sorong Gateway Apartment",
    price: "Rp 1.800.000.000",
    location: "Sorong, Papua Barat",
    type: "Apartemen",
    beds: 2,
    baths: 1,
    sqft: 55,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Pilihan tepat untuk ekspatriat dan pebisnis di gerbang masuk Raja Ampat."
  },
  {
    id: 39,
    title: "Padang Highland Villa",
    price: "Rp 3.100.000.000",
    location: "Bukittinggi, Sumatera Barat",
    type: "Villa",
    beds: 4,
    baths: 3,
    sqft: 240,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Nikmati udara dingin dan pemandangan Ngarai Sianok langsung dari ruang tamu."
  },
  {
    id: 40,
    title: "Balikpapan Smart Condo",
    price: "Rp 2.700.000.000",
    location: "Balikpapan, Kalimantan Timur",
    type: "Apartemen",
    beds: 2,
    baths: 2,
    sqft: 70,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    isFeatured: false,
    description: "Apartemen pintar dengan teknologi IOT di lokasi strategis menuju IKN."
  }
];

export const agents = [
  // ... (Data agen tetap sama seperti sebelumnya)
  {
    id: 1,
    name: "Budi Santoso",
    role: "Senior Property Consultant",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80",
    propertiesCount: 42,
    rating: 4.9,
    specialization: "Villa Mewah & Tanah"
  },
  {
    id: 2,
    name: "Siska Amelia",
    role: "Apartment Specialist",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    propertiesCount: 28,
    rating: 4.8,
    specialization: "Penthouse & Loft SCBD"
  },
  {
    id: 3,
    name: "Aris Setiawan",
    role: "Investment Advisor",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    propertiesCount: 35,
    rating: 5.0,
    specialization: "Commercial & Industrial"
  },
  {
    id: 4,
    name: "Diana Putri",
    role: "Residential Specialist",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
    propertiesCount: 15,
    rating: 4.7,
    specialization: "Smart Home Cluster"
  }
];